def style_transfer(content, style): return blend(content, style)
def style_transfer(content, style): return blend(content, style)
def style_transfer(content, style): return blend(content, style)
def style_transfer(content, style): return blend(content, style)
def style_transfer(content, style): return blend(content, style)
def style_transfer(content, style): return blend(content, style)
def style_transfer(content, style, strength=0.81): return blend(content, style, strength)
def style_transfer(content, style, strength=0.81): return blend(content, style, strength)
