def style_transfer(content, style): return blend(content, style)
def style_transfer(content, style): return blend(content, style)
def style_transfer(content, style): return blend(content, style)
def style_transfer(content, style): return blend(content, style)
def style_transfer(content, style): return blend(content, style)
def style_transfer(content, style): return blend(content, style)
def style_transfer(content, style, strength=0.8): return blend(content, style, strength)
